/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 --transform .\the_mill_ma.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Page1(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/Models/the_mill-center-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, 0.4, 0]}>
      <mesh castShadow receiveShadow geometry={nodes['m_House_Material_#81_0'].geometry} material={materials.Material_81} />
      <mesh castShadow receiveShadow geometry={nodes['m_House_Material_#158_0'].geometry} material={materials.Material_158} />
      <mesh castShadow receiveShadow geometry={nodes['m_House_Material_#2_0'].geometry} material={materials.Material_2} />
      <mesh castShadow receiveShadow geometry={nodes['m_House_Material_#1_0'].geometry} material={materials.Material_1} />
      <mesh castShadow receiveShadow geometry={nodes['m_WoodenBeams_Material_#25_0'].geometry} material={materials.Material_25} />
      <mesh castShadow receiveShadow geometry={nodes['m_Ground_Material_#58_0'].geometry} material={materials.Material_58} />
      <mesh castShadow receiveShadow geometry={nodes['m_Pier_Material_#31_0'].geometry} material={materials.Material_31} />
      <mesh castShadow receiveShadow geometry={nodes['m_StoneLedge_Material_#29_0'].geometry} material={materials.Material_29} />
      <mesh castShadow receiveShadow geometry={nodes['m_Clothline_Material_#26_0'].geometry} material={materials.Material_26} />
      <mesh castShadow receiveShadow geometry={nodes['m_Clothline_Material_#166_0'].geometry} material={materials.Material_166} />
      <mesh castShadow receiveShadow geometry={nodes['m_Rock_Material_#27_0'].geometry} material={materials.Material_27} />
      <mesh castShadow receiveShadow geometry={nodes['m_Fence_Material_#59_0'].geometry} material={materials.Material_59} />
      <mesh castShadow receiveShadow geometry={nodes['m_Barrel_Material_#30_0'].geometry} material={materials.Material_30} />
      <mesh castShadow receiveShadow geometry={nodes['m_Log_Material_#28_0'].geometry} material={materials.Material_28} />
      <mesh castShadow receiveShadow geometry={nodes['m_Tree_Material_#33_0'].geometry} material={materials.Material_33} />
      <mesh castShadow receiveShadow geometry={nodes['m_Tree_Material_#101_0'].geometry} material={materials.Material_101} />
      <mesh castShadow receiveShadow geometry={nodes['m_Tree_Material_#102_0'].geometry} material={materials.Material_102} />
      <mesh castShadow receiveShadow geometry={nodes['m_Tree_Material_#103_0'].geometry} material={materials.Material_103} />
      <mesh castShadow receiveShadow geometry={nodes['m_Tree_Material_#106_0'].geometry} material={materials.Material_106} />
      <mesh castShadow receiveShadow geometry={nodes['m_Grass_Material_#109_0'].geometry} material={materials.Material_109} />
      <mesh castShadow receiveShadow geometry={nodes['m_Bricks_Material_#32_0'].geometry} material={materials.Material_32} />
      <mesh geometry={nodes['m_Water_Material_#152_0'].geometry} material={materials.Material_152} />
      <mesh castShadow receiveShadow geometry={nodes['m_Plants_Material_#155_0'].geometry} material={materials.Material_155} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL+'/Models/the_mill-center-transformed.glb')
