/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 --transform .\greenhouse-center.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Page2(props) {
  const { nodes, materials } = useGLTF('/Models/greenhouse-center-transformed.glb')
  return (
    <group {...props} dispose={null} scale={0.6} position={[0, 0.4, 0]}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_Line_art_0.geometry} material={materials.Line_art} />
      <mesh castShadow receiveShadow geometry={nodes.Cube042_Glass_0.geometry} material={materials.Glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
      <mesh castShadow receiveShadow geometry={nodes.Circle010_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
      <mesh castShadow receiveShadow geometry={nodes.BezierCurve_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
      <mesh castShadow receiveShadow geometry={nodes.Circle031_Line_art_Green__0.geometry} material={materials.Line_art_Green} />
      <mesh castShadow receiveShadow geometry={nodes.Circle034_Material003_0.geometry} material={materials['Material.003']} />
      <mesh castShadow receiveShadow geometry={nodes.Circle055_Material004_0.geometry} material={materials['Material.004']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane021_Leaves_2_0.geometry} material={materials.Leaves_2} />
      <mesh castShadow receiveShadow geometry={nodes.Plane021_Leaves_1_0.geometry} material={materials.Leaves_1} />
      <mesh castShadow receiveShadow geometry={nodes.Plane013_Leaves_3_0.geometry} material={materials.Leaves_3} />
      <mesh castShadow receiveShadow geometry={nodes.Plane018_Leaves_4_0.geometry} material={materials.Leaves_4} />
      <mesh castShadow receiveShadow geometry={nodes.Plane015_Grass_0.geometry} material={materials.Grass} />
      <mesh castShadow receiveShadow geometry={nodes.Plane011_Leaves__drop_0.geometry} material={materials.Leaves__drop} />
      <mesh castShadow receiveShadow geometry={nodes.Plane124_Glow_0.geometry} material={materials.Glow} />
    </group>
  )
}

useGLTF.preload('/Models/greenhouse-center-transformed.glb')
