/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 --transform .\vacuumlego.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Page3(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/Models/vacuumlego-transformed.glb')
  return (
    <group {...props} dispose={null} scale={1.0} position={[0, 1.5, 0]}>
      <mesh castShadow geometry={nodes.Lego.geometry} material={materials.LegoMaterial} rotation={[0.268, 0.133, -1.222]} />
      <mesh castShadow geometry={nodes.Cube.geometry} material={materials.VacuumMaterial} scale={[1.496, 2.359, 3.105]} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL+'/Models/vacuumlego-transformed.glb')
